BlueCC/urls.py
# URL configuration for BlueCC project.
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
from django.conf.urls.static import static
from django.urls import path, include, re_path

from . import settings

urlpatterns = [
    path('', include('home.urls')),
    path('', include('user.urls')),
    path('', include('company.urls')),
    path('', include('job.urls')),
    path('', include('settings.urls')),
    path('', include('cv_management.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

job/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('job/suitable-job/', views.SuitableJob.as_view(), name='suitable_job'),
    path('job/applied-job/', views.AppliedJob.as_view(), name='applied_job'),
    path('job/apply-job/', views.ApplyJob.as_view(), name='apply_job'),
    path('job/saved-job/', views.SavedJob.as_view(), name='saved_job'),
    path('job/search-job/', views.SearchJob.as_view(), name='search_job'),
    path('job/detail-job/<int:jobdescription_id>', views.DetailJob.as_view(), name='detail_job'),
]

company/models.py
from django.db import models
from ckeditor.fields import RichTextField

from home.models import Account


class Company(models.Model):
    account = models.OneToOneField(Account, on_delete=models.CASCADE, primary_key=True)
    company_name = models.CharField(max_length=50, null=False, unique=True)
    description = RichTextField()
    address = models.CharField(max_length=100, null=True)
    number_of_employees = models.IntegerField(null=True, default=0)
    social_link = models.CharField(max_length=254, null=True)
    industry = models.CharField(max_length=50, null=True)
    followers = models.IntegerField(default=0)

    def __str__(self):
        return self.company_name

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>{% block title %}{% endblock %} | BlueCC</title>

    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/logo/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/logo/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/logo/favicon-32x32.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/logo/apple-touch-icon.png' %}">
    <link rel="manifest" href="{% static 'images/logo/site.webmanifest' %}">

    <!-- Flaticon CDN -->
    <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css"/>
    <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-straight/css/uicons-regular-straight.css"/>
    <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-solid-rounded/css/uicons-solid-rounded.css"/>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-solid-straight/css/uicons-solid-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-bold-rounded/css/uicons-bold-rounded.css'>
    <link rel="icon" href="https://www.flaticon.com/icon-fonts-most-downloaded?weight=regular&type=uicon" type="image/x-icon">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <script src="https://kit.fontawesome.com/6f688f08b3.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Slick carousel -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
          integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
          integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/toast.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/alert.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/preloading.css' %}" type="text/css"/>
    {% block css %}{% endblock %}

    <!-- JS -->

    {% block js %}{% endblock %}
</head>

<body>
{% block body %}
    {% include 'layout/preloading.html' %}
    <main class="container-fluid px-0">
        {% block header %}{% endblock %}

        {% block content %}{% endblock %}

        {% block footer %}{% endblock %}
    </main>
{% endblock %}
<script src="{% static 'js/toast.js' %}"></script>
{#<script src="{% static 'js/alert.js' %}"></script>#}
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/api.js' %}"></script>
{% block jsbody %}{% endblock %}
</body>
</html>

templates/layout/base_hf.html
{% extends 'layout/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css"/>
{% endblock %}

{% block header %}{% include 'layout/header.html' %}{% endblock %}

{% block footer %}{% include 'layout/footer.html' %}{% endblock %}

templates/layout/footer.html
<footer>
    <div class="logo">
        <span>BlueCC</span>
    </div>
    <div class="d-flex footer__info">
        <div class="footer__item">
            <h3 class="footer-h3">Về chúng tôi</h3>
            <ul>
                <li>Liên hệ</li>
                <li>Hỏi đáp</li>
                <li>Quy định bảo mật</li>
            </ul>
        </div>
        <div class="footer__item">
            <h3 class="footer-h3">Việc làm theo ngành nghề</h3>
            <ul>
                <li>Công nghệ thông tin</li>
                <li>Kế toán - Kiểm toán</li>
                <li>Kinh doanh</li>
                <li>Ngân hàng</li>
            </ul>
        </div>
        <div class="footer__item">
            <h3 class="footer-h3">Việc làm theo khu vực</h3>
            <ul>
                <li>Tp.Hồ Chí Minh</li>
                <li>Hà Nội</li>
                <li>Đà Nẵng</li>
            </ul>
        </div>
        <div class="footer__item">
            <h3 class="footer-h3">Theo dõi chúng tôi trên</h3>
            <ul>
                <li>Linked</li>
                <li>Facebook</li>
                <li>Instagram</li>
            </ul>
        </div>
    </div>
    <div class="text-center copy-right">
        <div>Copyright © Công Ty Cổ Phần BlueCC</div>
        <div>
            Đường Nguyễn Bình, Xã Nhơn Đức, huyện Nhà Bè, thành phố Hồ Chí Minh
        </div>
    </div>
</footer>

templates/layout/header.html
{% load static %}
<header class="header d-flex fixed-top">
    <div class="header__logo" style="width: 160px;">
        <img src="{% static 'images/logo/bg_logo.png' %}" alt="" width="100%"/>
    </div>
    <nav class="navbar navbar-expand-sm header__navbar">
        <div class="container-fluid">
            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'home' %}">Trang chủ</a>
                </li>
                <li class="nav-item hover-parent">
                    <a class="nav-link" href="javascript:void(0);">Việc làm</a>
                    <div class="hover-child lg left">
                        <ul>
                            <li><a href="{% url 'search_job' %}"><i class="fi fi-rr-search"></i>Tìm việc làm</a></li>
                            <li><a href="{% url 'saved_job' %}"><i class="fi fi-rs-heart"></i>Việc làm đã lưu</a></li>
                            <li><a href="{% url 'applied_job' %}"><i class="fi fi-rr-briefcase"></i>Việc làm đã ứng tuyển</a></li>
                            <li><a href="{% url 'suitable_job' %}"><i class="fi fi-rr-vote-yea"></i>Việc làm phù hợp</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item hover-parent">
                    <a class="nav-link" href="javascript:void(0);">Hồ sơ & CV</a>
                    <div class="hover-child left">
                        <ul>
                            <li><a href="{% url 'cv_management' %}"><i class="fi fi-rs-add-document"></i>Quản lí CV</a></li>
                            <li><a href="{% url 'cv_template' %}"><i class="fi fi-rs-document"></i>Mẫu CV</a></li>
                            <li><a href="{% url 'cv_major' %}"><i class="fi fi-rs-file-edit"></i>CV theo ngành</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item hover-parent">
                    <a class="nav-link" href="javascript:void(0);">Công ty</a>
                    <div class="hover-child left">
                        <ul>
                            <li><a href="{% url 'company_list' %}"><i class="fi fi-rs-building"></i>Danh sách công ty</a></li>
                            <li><a href="{% url 'company_top' %}"><i class="fi fi-rs-stars"></i>Top công ty</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="header__actions d-inline-flex">
        {% if request.user.is_authenticated %}
            <div class="actions__noti">
                <div class="icon"><i class="fi fi-rs-bell"></i></div>
            </div>
            <div class="actions__chat">
                <div class="icon"><i class="fi fi-rr-comment-alt"></i></div>
            </div>
            <div class="actions__user hover-parent">
                <img src="{{ request.user.avatar }}"
                     alt="Avatar của
                                 {% if request.user.user.full_name %}
                                    {{ request.user.user.full_name }}
                                {% else %}
                                    {{ request.user.company.company_name }}
                                {% endif %}"
                     class="actions__user-avatar"/>
                <span>
                    {% if request.user.is_superuser %}
                        {{ request.user.username }}
                    {% elif request.user.user.full_name %}
                        {{ request.user.user.full_name }}
                    {% else %}
                        {{ request.user.company.company_name }}
                    {% endif %}
                </span>
                <div class="actions__user-more hover-child lg">
                    <div class="actions__user-infor d-flex">
                        <img src="{{ request.user.avatar }}" alt="Avatar của
                                    {% if request.user.is_superuser %}
                                        {{ request.user.username }}
                                    {% elif request.user.user.full_name %}
                                        {{ request.user.user.full_name }}
                                    {% else %}
                                        {{ request.user.company.company_name }}
                                    {% endif %}"
                             class="actions__user-avatar"/>
                        <div class="actions__user-text">
                            <div class="actions__user-name">
                                {% if request.user.is_superuser %}
                                    {{ request.user.username }}
                                {% elif request.user.user.full_name %}
                                    {{ request.user.user.full_name }}
                                {% else %}
                                    {{ request.user.company.company_name }}
                                {% endif %}
                            </div>
                            <div class="small-text">
                                Mã ứng viên: <span class="text">#{{ request.user.id }}</span>
                            </div>
                            <div class="small-text">{{ request.user.email }}</div>
                        </div>
                    </div>
                    <ul class="actions__user-actions">
                        {% if request.user.is_superuser %}
                            <li class="actions__user-action">
                                <a href="{% url 'company_settings' %}"><i class="fi fi-rr-file-edit"></i>Thông tin doanh nghiệp</a>
                            </li>
                            <li class="actions__user-action">
                                <a href="{% url 'company_recruitment_management' %}"><i class="fa-solid fa-wand-magic-sparkles"></i>Quản lý bài tuyển dụng</a>
                            </li>
                            <li class="actions__user-action">
                                <a href="{% url 'profile_settings' %}"><i class="fi fi-rr-file-edit"></i>Chỉnh sửa thông tin</a>
                            </li>
                            <li class="actions__user-action">
                                <a href="{% url 'job_settings' %}"><i class="fi fi-rs-settings"></i>Cài đặt gợi ý việc làm</a>
                            </li>
                        {% elif perms.company.view_company %}
                            <li class="actions__user-action">
                                <a href="{% url 'company_settings' %}"><i class="fi fi-rr-file-edit"></i>Thông tin doanh nghiệp</a>
                            </li>
                            <li class="actions__user-action">
                                <a href="{% url 'company_recruitment_management' %}"><i class="fa-solid fa-wand-magic-sparkles"></i>Quản lý bài tuyển dụng</a>
                            </li>
                        {% else %}
                            <li class="actions__user-action">
                                <a href="{% url 'profile_settings' %}"><i class="fi fi-rr-file-edit"></i>Chỉnh sửa thông tin</a>
                            </li>
                            <li class="actions__user-action">
                                <a href="{% url 'job_settings' %}"><i class="fi fi-rs-settings"></i>Cài đặt gợi ý việc làm</a>
                            </li>
                        {% endif %}
                        <li class="actions__user-action">
                            <a href="{% url 'password_change' %}"><i class="fi fi-rr-lock"></i>Đổi mật khẩu</a>
                        </li>
                        <li class="actions__user-action">
                            <a href="{% url 'logout' %}"><i class="fi fi-rr-address-card"></i>Đăng xuất</a>
                        </li>
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="buttons d-flex align-items-center">
                <a href="{% url 'login' %}">
                    <button class="login-btn">Đăng nhập</button>
                </a>
                <a href="{% url 'signup' %}">
                    <button class="register-btn">Đăng kí</button>
                </a>
                <a href="{% url 'company_recruitment_management' %}">
                    <button class="btn btn-dark">Đăng bài tuyển dụng</button>
                </a>
            </div>
        {% endif %}
    </div>
</header>

templates/layout/preloading.html
<div id="loadingModal" class="modal">
    <div class="modal-content">
        <div class="loader"></div>
        <p>Loading...</p>
    </div>
</div>